name: client
description: A platform for deliberations
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  json_annotation: ^4.9.0
  crypto: ^3.0.2
  duration: ^3.0.13
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.8.0
  fluttertoast: ^8.2.4
  flutter_staggered_grid_view: ^0.7.0
  json_serializable: ^6.6.2
  linkify: ^5.0.0
  matomo_tracker: ^5.1.0
  normal: ^0.6.0
  platform_detect: ^2.0.11
  super_editor: ^0.3.0-dev.22
  super_editor_markdown: ^0.1.7

  uuid: ^4.1.0

  data_models:
    path: ../data_models
  numberpicker: ^2.1.2

  agora_rtc_engine:
    git:
      url: https://github.com/berkmancenter/Agora-Flutter-SDK.git
  firebase_auth: ^4.17.7
  firebase_core: ^2.26.0
  firebase_database: ^10.4.8
  cloud_firestore: ^4.15.7
  cloud_functions_web: ^4.7.1
  cloud_functions: ^4.6.7
  provider: ^6.1.2
  rxdart: ^0.27.7
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  http: ^1.2.2
  url_launcher: ^6.1.11
  responsive_builder: ^0.7.0
  datetime_picker_formfield: ^2.0.1
  flutter_form_builder: ^9.2.1
  flutter_markdown: ^0.6.15
  ntp: ^2.0.0
  transparent_image: ^2.0.1
  timezone: ^0.9.2
  pedantic: ^1.11.1
  sentry: ^8.7.0
  google_fonts: ^4.0.4
  universal_html: ^2.2.2
  js: ^0.6.5
  font_awesome_flutter: ^10.4.0
  flutter_portal: ^1.1.4

  horizontal_calendar_widget:
    git:
      url: https://github.com/berkmancenter/horizontal_calendar.git

  flutter_rating_bar: ^4.0.1
  flutter_reorderable_list: ^1.3.1
  image_picker: ^1.0.4
  mime_type: ^1.0.0
  flutter_linkify: ^6.0.0
  pointer_interceptor: ^0.9.3+5

  recase: ^4.1.0
  flutter_hooks: ^0.20.5
  quiver: ^3.2.1
  async: ^2.10.0
  beamer: ^1.6.0
  cloudinary_public: ^0.23.1
  dotted_border: ^2.1.0
  shared_preferences: ^2.2.2
  skeleton_text: ^3.0.1
  flutter_emoji: ^2.5.1
  flutter_scatter: ^0.2.0
  flutter_svg: ^2.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  logger: ^2.1.0
  synchronized: ^3.1.0
  clock: ^1.1.1
  metadata_fetch: ^0.4.1
  file_picker: ^5.3.1
  rainbow_color: ^2.0.1
  video_player: ^2.7.2
  csv: ^6.0.0
  simple_tooltip: ^1.2.0
  firebase_ui_firestore: ^1.6.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  random_string: ^2.3.1
  sentry_dart_plugin: ^2.0.0
  youtube_player_iframe: ^4.0.4

dependency_overrides:
  collection: ^1.19.0
  http_parser: ^4.1.0
  #flutter_reorderable_list:
  #  path: ../../flutter_reorderable_list

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - media/
    - assets/
    - assets/google_fonts/

# This section configures Sentry sentry-dart-plugin
# auth_token, org, and project come via environment variables in Github actions
sentry:
  upload_source_maps: true
  upload_debug_symbols: true
  upload_sources: true
  ignore_missing: true
