{{flutter_js}}
{{flutter_build_config}}

_flutter.loader.load({
  onEntrypointLoaded: async function(engineInitializer) {
    /*
     * Initialize the app runner inside the "flutter-container" element to 
     * use the Flutter Engine's CustomElementEmbeddingStrategy. This is a 
     * workaround to improve accessibility ratings by bypassing the viewport 
     * attributes generated by the FullPageEmbeddingStrategy.
     * 
     * Note: #flutter-container requires `touch-action: none` in CC to allow 
     * Flutter to handle scroll & drag events without the browser intercepting 
     * them first.
     */
    const appRunner = await engineInitializer.initializeEngine({
      hostElement: document.querySelector("#flutter-container")
    });
    await appRunner.runApp();
  }
});