coverage:
  status:
    project:
      default:
        informational: true
        if_ci_failed: ignore
    
    patch: 
      default:
        informational: true
        if_ci_failed: ignore
        
github_checks:
  annotations: false
