version: '3.7'

services:
  flutter:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: dev.Dockerfile
    networks:
      - flutter-network
    volumes:
      - ./client:/junto/junto/client
      - ./_dev/pubcache:/flutter/flutter/.pub-cache
      - homedir:/root
    ports:
      - "8000:8000"
      - "4000:4000"
      - "5000:5000"
      - "5001:5001"
      - "8080:8080"
      - "8085:8085"
      - "9000:9000"
      - "9005:9005"
      - "9099:9099"

networks:
  flutter-network:
    driver: bridge

volumes:
  homedir:
