name: combiner_cli
description: CLI utility for the M3U8 to MP4 combiner Firebase function
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
