// Mocks generated by Mockito 5.4.4 from annotations
// in client/test/lib/features/admin/presentation/data_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i14;

import 'package:client/core/data/services/clock_service.dart' as _i11;
import 'package:client/core/data/services/firestore_database.dart' as _i15;
import 'package:client/core/utils/extensions.dart' as _i7;
import 'package:client/core/utils/firestore_utils.dart' as _i6;
import 'package:client/core/widgets/navbar/nav_bar_provider.dart' as _i4;
import 'package:client/features/community/data/providers/community_provider.dart'
    as _i12;
import 'package:client/features/events/data/services/firestore_event_service.dart'
    as _i16;
import 'package:client/features/events/features/event_page/presentation/views/survey_dialog.dart'
    as _i17;
import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:data_models/community/community.dart' as _i5;
import 'package:data_models/resources/community_resource.dart' as _i13;
import 'package:data_models/templates/template.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBehaviorSubject_0<T1> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T1> {
  _FakeBehaviorSubject_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSubscription_1<T1> extends _i1.SmartFake
    implements _i3.StreamSubscription<T1> {
  _FakeStreamSubscription_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_2<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_3 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNavBarProvider_4 extends _i1.SmartFake
    implements _i4.NavBarProvider {
  _FakeNavBarProvider_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommunity_5 extends _i1.SmartFake implements _i5.Community {
  _FakeCommunity_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBehaviorSubjectWrapper_6<T> extends _i1.SmartFake
    implements _i6.BehaviorSubjectWrapper<T> {
  _FakeBehaviorSubjectWrapper_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommunitySettings_7 extends _i1.SmartFake
    implements _i5.CommunitySettings {
  _FakeCommunitySettings_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventSettings_8 extends _i1.SmartFake implements _i7.EventSettings {
  _FakeEventSettings_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$EventCopyWith_9<$Res> extends _i1.SmartFake
    implements _i7.$EventCopyWith<$Res> {
  _Fake$EventCopyWith_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_10 extends _i1.SmartFake implements Duration {
  _FakeDuration_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_11 extends _i1.SmartFake
    implements _i8.FirebaseFirestore {
  _FakeFirebaseFirestore_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_12<T extends Object?> extends _i1.SmartFake
    implements _i8.DocumentReference<T> {
  _FakeDocumentReference_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_13<T extends Object?> extends _i1.SmartFake
    implements _i8.CollectionReference<T> {
  _FakeCollectionReference_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTemplate_14 extends _i1.SmartFake implements _i9.Template {
  _FakeTemplate_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuery_15<T extends Object?> extends _i1.SmartFake
    implements _i8.Query<T> {
  _FakeQuery_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvent_16 extends _i1.SmartFake implements _i7.Event {
  _FakeEvent_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BehaviorSubjectWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockBehaviorSubjectWrapper<T> extends _i1.Mock
    implements _i6.BehaviorSubjectWrapper<T> {
  MockBehaviorSubjectWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BehaviorSubject<T> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _FakeBehaviorSubject_0<T>(
          this,
          Invocation.getter(#stream),
        ),
      ) as _i2.BehaviorSubject<T>);

  @override
  _i3.StreamSubscription<dynamic> get streamSubscription => (super.noSuchMethod(
        Invocation.getter(#streamSubscription),
        returnValue: _FakeStreamSubscription_1<dynamic>(
          this,
          Invocation.getter(#streamSubscription),
        ),
      ) as _i3.StreamSubscription<dynamic>);

  @override
  bool get isBroadcast => (super.noSuchMethod(
        Invocation.getter(#isBroadcast),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<int> get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<bool> get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<T> get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.getter(#first),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.getter(#first),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.getter(#last),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.getter(#last),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.getter(#single),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.getter(#single),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.StreamSubscription<T> listen(
    void Function(T)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [onData],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_1<T>(
          this,
          Invocation.method(
            #listen,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i3.StreamSubscription<T>);

  @override
  _i3.Stream<T> asBroadcastStream({
    void Function(_i3.StreamSubscription<T>)? onListen,
    void Function(_i3.StreamSubscription<T>)? onCancel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #asBroadcastStream,
          [],
          {
            #onListen: onListen,
            #onCancel: onCancel,
          },
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<T> where(bool Function(T)? test) => (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<S> map<S>(S Function(T)? convert) => (super.noSuchMethod(
        Invocation.method(
          #map,
          [convert],
        ),
        returnValue: _i3.Stream<S>.empty(),
      ) as _i3.Stream<S>);

  @override
  _i3.Stream<E> asyncMap<E>(_i3.FutureOr<E> Function(T)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncMap,
          [convert],
        ),
        returnValue: _i3.Stream<E>.empty(),
      ) as _i3.Stream<E>);

  @override
  _i3.Stream<E> asyncExpand<E>(_i3.Stream<E>? Function(T)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncExpand,
          [convert],
        ),
        returnValue: _i3.Stream<E>.empty(),
      ) as _i3.Stream<E>);

  @override
  _i3.Stream<T> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleError,
          [onError],
          {#test: test},
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<S> expand<S>(Iterable<S> Function(T)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [convert],
        ),
        returnValue: _i3.Stream<S>.empty(),
      ) as _i3.Stream<S>);

  @override
  _i3.Future<dynamic> pipe(_i3.StreamConsumer<T>? streamConsumer) =>
      (super.noSuchMethod(
        Invocation.method(
          #pipe,
          [streamConsumer],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  _i3.Stream<S> transform<S>(_i3.StreamTransformer<T, S>? streamTransformer) =>
      (super.noSuchMethod(
        Invocation.method(
          #transform,
          [streamTransformer],
        ),
        returnValue: _i3.Stream<S>.empty(),
      ) as _i3.Stream<S>);

  @override
  _i3.Future<T> reduce(
          T Function(
            T,
            T,
          )? combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #reduce,
                  [combine],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #reduce,
                [combine],
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<S> fold<S>(
    S? initialValue,
    S Function(
      S,
      T,
    )? combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<S>(
                this,
                Invocation.method(
                  #fold,
                  [
                    initialValue,
                    combine,
                  ],
                ),
              ),
              (S v) => _i3.Future<S>.value(v),
            ) ??
            _FakeFuture_2<S>(
              this,
              Invocation.method(
                #fold,
                [
                  initialValue,
                  combine,
                ],
              ),
            ),
      ) as _i3.Future<S>);

  @override
  _i3.Future<String> join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i3.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<bool> contains(Object? needle) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [needle],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> forEach(void Function(T)? action) => (super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> every(bool Function(T)? test) => (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> any(bool Function(T)? test) => (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Stream<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: _i3.Stream<R>.empty(),
      ) as _i3.Stream<R>);

  @override
  _i3.Future<List<T>> toList() => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
        ),
        returnValue: _i3.Future<List<T>>.value(<T>[]),
      ) as _i3.Future<List<T>>);

  @override
  _i3.Future<Set<T>> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue: _i3.Future<Set<T>>.value(<T>{}),
      ) as _i3.Future<Set<T>>);

  @override
  _i3.Future<E> drain<E>([E? futureValue]) => (super.noSuchMethod(
        Invocation.method(
          #drain,
          [futureValue],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<E>(
                this,
                Invocation.method(
                  #drain,
                  [futureValue],
                ),
              ),
              (E v) => _i3.Future<E>.value(v),
            ) ??
            _FakeFuture_2<E>(
              this,
              Invocation.method(
                #drain,
                [futureValue],
              ),
            ),
      ) as _i3.Future<E>);

  @override
  _i3.Stream<T> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<T> takeWhile(bool Function(T)? test) => (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<T> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<T> skipWhile(bool Function(T)? test) => (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Stream<T> distinct(
          [bool Function(
            T,
            T,
          )? equals]) =>
      (super.noSuchMethod(
        Invocation.method(
          #distinct,
          [equals],
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);

  @override
  _i3.Future<T> firstWhere(
    bool Function(T)? test, {
    T Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #firstWhere,
                  [test],
                  {#orElse: orElse},
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #firstWhere,
                [test],
                {#orElse: orElse},
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> lastWhere(
    bool Function(T)? test, {
    T Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #lastWhere,
                  [test],
                  {#orElse: orElse},
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #lastWhere,
                [test],
                {#orElse: orElse},
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> singleWhere(
    bool Function(T)? test, {
    T Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #singleWhere,
                  [test],
                  {#orElse: orElse},
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #singleWhere,
                [test],
                {#orElse: orElse},
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #elementAt,
                  [index],
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_2<T>(
              this,
              Invocation.method(
                #elementAt,
                [index],
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Stream<T> timeout(
    Duration? timeLimit, {
    void Function(_i3.EventSink<T>)? onTimeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #timeout,
          [timeLimit],
          {#onTimeout: onTimeout},
        ),
        returnValue: _i3.Stream<T>.empty(),
      ) as _i3.Stream<T>);
}

/// A class which mocks [ClockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClockService extends _i1.Mock implements _i11.ClockService {
  MockClockService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<DateTime> getServerTimestamp() => (super.noSuchMethod(
        Invocation.method(
          #getServerTimestamp,
          [],
        ),
        returnValue: _i3.Future<DateTime>.value(_FakeDateTime_3(
          this,
          Invocation.method(
            #getServerTimestamp,
            [],
          ),
        )),
      ) as _i3.Future<DateTime>);

  @override
  DateTime now() => (super.noSuchMethod(
        Invocation.method(
          #now,
          [],
        ),
        returnValue: _FakeDateTime_3(
          this,
          Invocation.method(
            #now,
            [],
          ),
        ),
      ) as DateTime);
}

/// A class which mocks [CommunityProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityProvider extends _i1.Mock implements _i12.CommunityProvider {
  MockCommunityProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.NavBarProvider get navBarProvider => (super.noSuchMethod(
        Invocation.getter(#navBarProvider),
        returnValue: _FakeNavBarProvider_4(
          this,
          Invocation.getter(#navBarProvider),
        ),
      ) as _i4.NavBarProvider);

  @override
  bool get enableHostless => (super.noSuchMethod(
        Invocation.getter(#enableHostless),
        returnValue: false,
      ) as bool);

  @override
  _i5.Community get community => (super.noSuchMethod(
        Invocation.getter(#community),
        returnValue: _FakeCommunity_5(
          this,
          Invocation.getter(#community),
        ),
      ) as _i5.Community);

  @override
  String get communityId => (super.noSuchMethod(
        Invocation.getter(#communityId),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#communityId),
        ),
      ) as String);

  @override
  String get displayId => (super.noSuchMethod(
        Invocation.getter(#displayId),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#displayId),
        ),
      ) as String);

  @override
  _i3.Stream<_i5.Community> get communityStream => (super.noSuchMethod(
        Invocation.getter(#communityStream),
        returnValue: _i3.Stream<_i5.Community>.empty(),
      ) as _i3.Stream<_i5.Community>);

  @override
  _i3.Stream<List<_i5.Featured>> get featuredStream => (super.noSuchMethod(
        Invocation.getter(#featuredStream),
        returnValue: _i3.Stream<List<_i5.Featured>>.empty(),
      ) as _i3.Stream<List<_i5.Featured>>);

  @override
  _i6.BehaviorSubjectWrapper<List<_i13.CommunityResource>>
      get resourcesStream => (super.noSuchMethod(
            Invocation.getter(#resourcesStream),
            returnValue:
                _FakeBehaviorSubjectWrapper_6<List<_i13.CommunityResource>>(
              this,
              Invocation.getter(#resourcesStream),
            ),
          ) as _i6.BehaviorSubjectWrapper<List<_i13.CommunityResource>>);

  @override
  List<_i5.Featured> get featuredItems => (super.noSuchMethod(
        Invocation.getter(#featuredItems),
        returnValue: <_i5.Featured>[],
      ) as List<_i5.Featured>);

  @override
  bool get hasResources => (super.noSuchMethod(
        Invocation.getter(#hasResources),
        returnValue: false,
      ) as bool);

  @override
  bool get hasTemplates => (super.noSuchMethod(
        Invocation.getter(#hasTemplates),
        returnValue: false,
      ) as bool);

  @override
  _i5.CommunitySettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeCommunitySettings_7(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i5.CommunitySettings);

  @override
  _i7.EventSettings get eventSettings => (super.noSuchMethod(
        Invocation.getter(#eventSettings),
        returnValue: _FakeEventSettings_8(
          this,
          Invocation.getter(#eventSettings),
        ),
      ) as _i7.EventSettings);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void initialize() => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadResources() => super.noSuchMethod(
        Invocation.method(
          #loadResources,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> updateBanner(String? url) => (super.noSuchMethod(
        Invocation.method(
          #updateBanner,
          [url],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfilePic(String? url) => (super.noSuchMethod(
        Invocation.method(
          #updateProfilePic,
          [url],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> donationsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #donationsEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> prePostEnabled() => (super.noSuchMethod(
        Invocation.method(
          #prePostEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> addNewOnboardingStep(_i5.OnboardingStep? onboardingStep) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNewOnboardingStep,
          [onboardingStep],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool isOnboardingStepCompleted(_i5.OnboardingStep? onboardingStep) =>
      (super.noSuchMethod(
        Invocation.method(
          #isOnboardingStepCompleted,
          [onboardingStep],
        ),
        returnValue: false,
      ) as bool);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Event].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvent extends _i1.Mock implements _i7.Event {
  MockEvent() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.EventType get eventType => (super.noSuchMethod(
        Invocation.getter(#eventType),
        returnValue: _i7.EventType.hosted,
      ) as _i7.EventType);

  @override
  bool get useParticipantCountEstimate => (super.noSuchMethod(
        Invocation.getter(#useParticipantCountEstimate),
        returnValue: false,
      ) as bool);

  @override
  bool get isLiveStream => (super.noSuchMethod(
        Invocation.getter(#isLiveStream),
        returnValue: false,
      ) as bool);

  @override
  bool get isHosted => (super.noSuchMethod(
        Invocation.getter(#isHosted),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPreEventData => (super.noSuchMethod(
        Invocation.getter(#hasPreEventData),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPostEventData => (super.noSuchMethod(
        Invocation.getter(#hasPostEventData),
        returnValue: false,
      ) as bool);

  @override
  String get fullPath => (super.noSuchMethod(
        Invocation.getter(#fullPath),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#fullPath),
        ),
      ) as String);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i7.EventStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i7.EventStatus.active,
      ) as _i7.EventStatus);

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  String get communityId => (super.noSuchMethod(
        Invocation.getter(#communityId),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#communityId),
        ),
      ) as String);

  @override
  String get templateId => (super.noSuchMethod(
        Invocation.getter(#templateId),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#templateId),
        ),
      ) as String);

  @override
  String get creatorId => (super.noSuchMethod(
        Invocation.getter(#creatorId),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#creatorId),
        ),
      ) as String);

  @override
  bool get isPublic => (super.noSuchMethod(
        Invocation.getter(#isPublic),
        returnValue: false,
      ) as bool);

  @override
  List<_i7.AgendaItem> get agendaItems => (super.noSuchMethod(
        Invocation.getter(#agendaItems),
        returnValue: <_i7.AgendaItem>[],
      ) as List<_i7.AgendaItem>);

  @override
  bool get isLocked => (super.noSuchMethod(
        Invocation.getter(#isLocked),
        returnValue: false,
      ) as bool);

  @override
  int get durationInMinutes => (super.noSuchMethod(
        Invocation.getter(#durationInMinutes),
        returnValue: 0,
      ) as int);

  @override
  _i7.$EventCopyWith<_i7.Event> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$EventCopyWith_9<_i7.Event>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i7.$EventCopyWith<_i7.Event>);

  @override
  Duration timeUntilScheduledStart(DateTime? now) => (super.noSuchMethod(
        Invocation.method(
          #timeUntilScheduledStart,
          [now],
        ),
        returnValue: _FakeDuration_10(
          this,
          Invocation.method(
            #timeUntilScheduledStart,
            [now],
          ),
        ),
      ) as Duration);

  @override
  Duration timeUntilWaitingRoomFinished(DateTime? now) => (super.noSuchMethod(
        Invocation.method(
          #timeUntilWaitingRoomFinished,
          [now],
        ),
        returnValue: _FakeDuration_10(
          this,
          Invocation.method(
            #timeUntilWaitingRoomFinished,
            [now],
          ),
        ),
      ) as Duration);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [FirestoreDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreDatabase extends _i1.Mock implements _i15.FirestoreDatabase {
  MockFirestoreDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_11(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i8.FirebaseFirestore);

  @override
  _i8.DocumentReference<Map<String, dynamic>> communityRef(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #communityRef,
          [id],
        ),
        returnValue: _FakeDocumentReference_12<Map<String, dynamic>>(
          this,
          Invocation.method(
            #communityRef,
            [id],
          ),
        ),
      ) as _i8.DocumentReference<Map<String, dynamic>>);

  @override
  _i8.CollectionReference<Map<String, dynamic>> templatesCollection(
          String? communityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #templatesCollection,
          [communityId],
        ),
        returnValue: _FakeCollectionReference_13<Map<String, dynamic>>(
          this,
          Invocation.method(
            #templatesCollection,
            [communityId],
          ),
        ),
      ) as _i8.CollectionReference<Map<String, dynamic>>);

  @override
  _i8.DocumentReference<Map<String, dynamic>> templateReference({
    required String? communityId,
    required String? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #templateReference,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
          },
        ),
        returnValue: _FakeDocumentReference_12<Map<String, dynamic>>(
          this,
          Invocation.method(
            #templateReference,
            [],
            {
              #communityId: communityId,
              #templateId: templateId,
            },
          ),
        ),
      ) as _i8.DocumentReference<Map<String, dynamic>>);

  @override
  String generateNewDocId({required String? collectionPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateNewDocId,
          [],
          {#collectionPath: collectionPath},
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #generateNewDocId,
            [],
            {#collectionPath: collectionPath},
          ),
        ),
      ) as String);

  @override
  _i3.Future<List<_i5.Community>> allPublicCommunities() => (super.noSuchMethod(
        Invocation.method(
          #allPublicCommunities,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Community>>.value(<_i5.Community>[]),
      ) as _i3.Future<List<_i5.Community>>);

  @override
  _i3.Future<_i5.Community?> getCommunity(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCommunity,
          [id],
        ),
        returnValue: _i3.Future<_i5.Community?>.value(),
      ) as _i3.Future<_i5.Community?>);

  @override
  _i3.Future<List<_i5.Community?>> getCommunityDocuments(
          List<String>? communityIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommunityDocuments,
          [communityIds],
        ),
        returnValue: _i3.Future<List<_i5.Community?>>.value(<_i5.Community?>[]),
      ) as _i3.Future<List<_i5.Community?>>);

  @override
  _i3.Stream<List<_i5.Community>> communitiesUserIsOwnerOf(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #communitiesUserIsOwnerOf,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i5.Community>>.empty(),
      ) as _i3.Stream<List<_i5.Community>>);

  @override
  String generateNewCommunityId() => (super.noSuchMethod(
        Invocation.method(
          #generateNewCommunityId,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #generateNewCommunityId,
            [],
          ),
        ),
      ) as String);

  @override
  _i6.BehaviorSubjectWrapper<_i5.Community> communityStream(
          String? displayId) =>
      (super.noSuchMethod(
        Invocation.method(
          #communityStream,
          [displayId],
        ),
        returnValue: _FakeBehaviorSubjectWrapper_6<_i5.Community>(
          this,
          Invocation.method(
            #communityStream,
            [displayId],
          ),
        ),
      ) as _i6.BehaviorSubjectWrapper<_i5.Community>);

  @override
  _i3.Future<List<_i9.Template>> allCommunityTemplates(
    String? communityId, {
    bool? includeRemovedTemplates = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #allCommunityTemplates,
          [communityId],
          {#includeRemovedTemplates: includeRemovedTemplates},
        ),
        returnValue: _i3.Future<List<_i9.Template>>.value(<_i9.Template>[]),
      ) as _i3.Future<List<_i9.Template>>);

  @override
  _i3.Stream<bool> communityHasTemplatesStream(String? communityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #communityHasTemplatesStream,
          [communityId],
        ),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i3.Stream<List<_i9.Template>> communityTemplatesStream(
          String? communityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #communityTemplatesStream,
          [communityId],
        ),
        returnValue: _i3.Stream<List<_i9.Template>>.empty(),
      ) as _i3.Stream<List<_i9.Template>>);

  @override
  _i3.Future<_i9.Template?> getTemplate(
    String? communityId,
    String? templateId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTemplate,
          [
            communityId,
            templateId,
          ],
        ),
        returnValue: _i3.Future<_i9.Template?>.value(),
      ) as _i3.Future<_i9.Template?>);

  @override
  _i3.Future<_i9.Template> communityTemplate({
    required String? communityId,
    required String? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #communityTemplate,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
          },
        ),
        returnValue: _i3.Future<_i9.Template>.value(_FakeTemplate_14(
          this,
          Invocation.method(
            #communityTemplate,
            [],
            {
              #communityId: communityId,
              #templateId: templateId,
            },
          ),
        )),
      ) as _i3.Future<_i9.Template>);

  @override
  _i3.Stream<_i9.Template?> templateStream({
    required String? communityId,
    required String? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #templateStream,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
          },
        ),
        returnValue: _i3.Stream<_i9.Template?>.empty(),
      ) as _i3.Stream<_i9.Template?>);

  @override
  _i6.BehaviorSubjectWrapper<List<_i5.Featured>> getCommunityFeaturedItems(
          String? communityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommunityFeaturedItems,
          [communityId],
        ),
        returnValue: _FakeBehaviorSubjectWrapper_6<List<_i5.Featured>>(
          this,
          Invocation.method(
            #getCommunityFeaturedItems,
            [communityId],
          ),
        ),
      ) as _i6.BehaviorSubjectWrapper<List<_i5.Featured>>);

  @override
  _i3.Future<void> updateFeaturedItem({
    required String? communityId,
    required String? documentId,
    required _i5.Featured? featured,
    required bool? isFeatured,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFeaturedItem,
          [],
          {
            #communityId: communityId,
            #documentId: documentId,
            #featured: featured,
            #isFeatured: isFeatured,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i9.Template> createTemplate({
    required String? communityId,
    required _i9.Template? template,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTemplate,
          [],
          {
            #communityId: communityId,
            #template: template,
          },
        ),
        returnValue: _i3.Future<_i9.Template>.value(_FakeTemplate_14(
          this,
          Invocation.method(
            #createTemplate,
            [],
            {
              #communityId: communityId,
              #template: template,
            },
          ),
        )),
      ) as _i3.Future<_i9.Template>);

  @override
  _i3.Future<void> updateTemplate({
    required String? communityId,
    required _i9.Template? template,
    required Iterable<String>? keys,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTemplate,
          [],
          {
            #communityId: communityId,
            #template: template,
            #keys: keys,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> upsertTemplateAgendaItem({
    required String? communityId,
    required String? templateId,
    required _i7.AgendaItem? updatedItem,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertTemplateAgendaItem,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #updatedItem: updatedItem,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTemplateAgendaItem({
    required String? communityId,
    required String? templateId,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTemplateAgendaItem,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #itemId: itemId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTemplateAgendaOrdering({
    required String? communityId,
    required String? templateId,
    required List<String>? ordering,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTemplateAgendaOrdering,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #ordering: ordering,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.Template>> getActiveTemplatesFromCommunities(
          List<String>? communityIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveTemplatesFromCommunities,
          [communityIds],
        ),
        returnValue: _i3.Future<List<_i9.Template>>.value(<_i9.Template>[]),
      ) as _i3.Future<List<_i9.Template>>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [FirestoreEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreEventService extends _i1.Mock
    implements _i16.FirestoreEventService {
  MockFirestoreEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<DateTime> get currentTimeAsync => (super.noSuchMethod(
        Invocation.getter(#currentTimeAsync),
        returnValue: _i3.Future<DateTime>.value(_FakeDateTime_3(
          this,
          Invocation.getter(#currentTimeAsync),
        )),
      ) as _i3.Future<DateTime>);

  @override
  _i8.CollectionReference<Map<String, dynamic>> eventsCollection({
    required String? communityId,
    required String? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #eventsCollection,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
          },
        ),
        returnValue: _FakeCollectionReference_13<Map<String, dynamic>>(
          this,
          Invocation.method(
            #eventsCollection,
            [],
            {
              #communityId: communityId,
              #templateId: templateId,
            },
          ),
        ),
      ) as _i8.CollectionReference<Map<String, dynamic>>);

  @override
  _i8.DocumentReference<Map<String, dynamic>> eventReference({
    required String? communityId,
    required String? templateId,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #eventReference,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeDocumentReference_12<Map<String, dynamic>>(
          this,
          Invocation.method(
            #eventReference,
            [],
            {
              #communityId: communityId,
              #templateId: templateId,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i8.DocumentReference<Map<String, dynamic>>);

  @override
  _i6.BehaviorSubjectWrapper<List<_i7.Event>> communityEvents(
          {required String? communityId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #communityEvents,
          [],
          {#communityId: communityId},
        ),
        returnValue: _FakeBehaviorSubjectWrapper_6<List<_i7.Event>>(
          this,
          Invocation.method(
            #communityEvents,
            [],
            {#communityId: communityId},
          ),
        ),
      ) as _i6.BehaviorSubjectWrapper<List<_i7.Event>>);

  @override
  _i6.BehaviorSubjectWrapper<List<_i7.Event>> futurePublicEvents({
    required String? communityId,
    required String? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #futurePublicEvents,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
          },
        ),
        returnValue: _FakeBehaviorSubjectWrapper_6<List<_i7.Event>>(
          this,
          Invocation.method(
            #futurePublicEvents,
            [],
            {
              #communityId: communityId,
              #templateId: templateId,
            },
          ),
        ),
      ) as _i6.BehaviorSubjectWrapper<List<_i7.Event>>);

  @override
  _i3.Future<List<_i7.Event>> getUpcomingPublicEventsFuture({
    required String? communityId,
    required String? templateId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingPublicEventsFuture,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
          },
        ),
        returnValue: _i3.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i3.Future<List<_i7.Event>>);

  @override
  _i3.Future<List<_i7.Event>> allPublicEventsFuture([int? limit = 100]) =>
      (super.noSuchMethod(
        Invocation.method(
          #allPublicEventsFuture,
          [limit],
        ),
        returnValue: _i3.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i3.Future<List<_i7.Event>>);

  @override
  _i6.BehaviorSubjectWrapper<List<_i7.Event>> futurePublicEventsForCommunity(
          {required String? communityId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #futurePublicEventsForCommunity,
          [],
          {#communityId: communityId},
        ),
        returnValue: _FakeBehaviorSubjectWrapper_6<List<_i7.Event>>(
          this,
          Invocation.method(
            #futurePublicEventsForCommunity,
            [],
            {#communityId: communityId},
          ),
        ),
      ) as _i6.BehaviorSubjectWrapper<List<_i7.Event>>);

  @override
  _i3.Future<List<_i7.Event>> userEventsForCommunity() => (super.noSuchMethod(
        Invocation.method(
          #userEventsForCommunity,
          [],
        ),
        returnValue: _i3.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i3.Future<List<_i7.Event>>);

  @override
  _i3.Future<bool> userHasParticipatedInTemplate(
          {required String? templateId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #userHasParticipatedInTemplate,
          [],
          {#templateId: templateId},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i6.BehaviorSubjectWrapper<_i7.Event> eventStream({
    required String? communityId,
    required String? templateId,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #eventStream,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeBehaviorSubjectWrapper_6<_i7.Event>(
          this,
          Invocation.method(
            #eventStream,
            [],
            {
              #communityId: communityId,
              #templateId: templateId,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i6.BehaviorSubjectWrapper<_i7.Event>);

  @override
  _i3.Stream<bool> communityHasEvents({required String? communityId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #communityHasEvents,
          [],
          {#communityId: communityId},
        ),
        returnValue: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);

  @override
  _i6.BehaviorSubjectWrapper<List<_i7.Participant>> eventParticipantsStream({
    required String? communityId,
    required String? templateId,
    required String? eventId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #eventParticipantsStream,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #eventId: eventId,
          },
        ),
        returnValue: _FakeBehaviorSubjectWrapper_6<List<_i7.Participant>>(
          this,
          Invocation.method(
            #eventParticipantsStream,
            [],
            {
              #communityId: communityId,
              #templateId: templateId,
              #eventId: eventId,
            },
          ),
        ),
      ) as _i6.BehaviorSubjectWrapper<List<_i7.Participant>>);

  @override
  _i3.Stream<_i7.Participant> eventParticipantStream({
    required String? communityId,
    required String? templateId,
    required String? eventId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #eventParticipantStream,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #eventId: eventId,
            #userId: userId,
          },
        ),
        returnValue: _i3.Stream<_i7.Participant>.empty(),
      ) as _i3.Stream<_i7.Participant>);

  @override
  _i3.Future<List<_i7.Event>> getEventsFromPaths(
    String? communityId,
    List<String>? documentPaths,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsFromPaths,
          [
            communityId,
            documentPaths,
          ],
        ),
        returnValue: _i3.Future<List<_i7.Event>>.value(<_i7.Event>[]),
      ) as _i3.Future<List<_i7.Event>>);

  @override
  _i8.Query<Map<String, dynamic>> eventParticipantsQuery(
          {required _i7.Event? event}) =>
      (super.noSuchMethod(
        Invocation.method(
          #eventParticipantsQuery,
          [],
          {#event: event},
        ),
        returnValue: _FakeQuery_15<Map<String, dynamic>>(
          this,
          Invocation.method(
            #eventParticipantsQuery,
            [],
            {#event: event},
          ),
        ),
      ) as _i8.Query<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i7.Participant>> getEventParticipants(
          {required _i7.Event? event}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventParticipants,
          [],
          {#event: event},
        ),
        returnValue:
            _i3.Future<List<_i7.Participant>>.value(<_i7.Participant>[]),
      ) as _i3.Future<List<_i7.Participant>>);

  @override
  _i3.Future<_i7.PrivateLiveStreamInfo?> liveStreamPrivateInfo(
          {required _i7.Event? event}) =>
      (super.noSuchMethod(
        Invocation.method(
          #liveStreamPrivateInfo,
          [],
          {#event: event},
        ),
        returnValue: _i3.Future<_i7.PrivateLiveStreamInfo?>.value(),
      ) as _i3.Future<_i7.PrivateLiveStreamInfo?>);

  @override
  _i3.Future<_i7.Event> createEventIfNotExists({
    required _i7.Event? event,
    _i7.PrivateLiveStreamInfo? privateLiveStreamInfo,
    bool? record = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEventIfNotExists,
          [],
          {
            #event: event,
            #privateLiveStreamInfo: privateLiveStreamInfo,
            #record: record,
          },
        ),
        returnValue: _i3.Future<_i7.Event>.value(_FakeEvent_16(
          this,
          Invocation.method(
            #createEventIfNotExists,
            [],
            {
              #event: event,
              #privateLiveStreamInfo: privateLiveStreamInfo,
              #record: record,
            },
          ),
        )),
      ) as _i3.Future<_i7.Event>);

  @override
  _i3.Future<void> updateEvent({
    required _i7.Event? event,
    required Iterable<String>? keys,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [],
          {
            #event: event,
            #keys: keys,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addLiveStreamEventDetails({
    required _i7.Event? event,
    _i7.PrivateLiveStreamInfo? privateLiveStreamInfo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLiveStreamEventDetails,
          [],
          {
            #event: event,
            #privateLiveStreamInfo: privateLiveStreamInfo,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> joinEvent({
    required String? communityId,
    required String? templateId,
    required String? eventId,
    String? externalCommunityId,
    bool? setAttendeeStatus = true,
    _i17.SurveyDialogResult? breakoutRoomSurveyResults,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinEvent,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #eventId: eventId,
            #externalCommunityId: externalCommunityId,
            #setAttendeeStatus: setAttendeeStatus,
            #breakoutRoomSurveyResults: breakoutRoomSurveyResults,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeParticipant({
    required String? communityId,
    required String? templateId,
    required String? eventId,
    required String? participantId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeParticipant,
          [],
          {
            #communityId: communityId,
            #templateId: templateId,
            #eventId: eventId,
            #participantId: participantId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> upsertAgendaItem({
    required _i7.Event? event,
    required _i7.AgendaItem? updatedItem,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertAgendaItem,
          [],
          {
            #event: event,
            #updatedItem: updatedItem,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setAgendaItemsLegacy({
    required _i7.Event? event,
    required List<_i7.AgendaItem>? agendaItems,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAgendaItemsLegacy,
          [],
          {
            #event: event,
            #agendaItems: agendaItems,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTemplateAgendaItem({
    required _i7.Event? event,
    required String? itemId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTemplateAgendaItem,
          [],
          {
            #event: event,
            #itemId: itemId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateAgendaOrdering({
    required _i7.Event? event,
    required List<String>? ordering,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAgendaOrdering,
          [],
          {
            #event: event,
            #ordering: ordering,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> kickParticipant({
    required _i7.Event? event,
    required String? kickedUserId,
    bool? lockRoom = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #kickParticipant,
          [],
          {
            #event: event,
            #kickedUserId: kickedUserId,
            #lockRoom: lockRoom,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateParticipantBreakoutSurveyAnswers({
    required _i7.Event? event,
    bool? lockRoom = false,
    required _i17.SurveyDialogResult? surveyDialogResult,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateParticipantBreakoutSurveyAnswers,
          [],
          {
            #event: event,
            #lockRoom: lockRoom,
            #surveyDialogResult: surveyDialogResult,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
