name: functions
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  csv: ^6.0.0
  functions_framework: ^0.4.0
  gsheets: ^0.5.0
  json_annotation: ^4.9.0
  quiver: ^3.2.2
  shelf: ^1.0.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.2.1
  dart_flutter_team_lints: ^3.0.0
  functions_framework_builder: ^0.4.7
  http: ^1.0.0
  json_serializable: ^6.6.0
  test: ^1.21.6
  test_process: ^2.0.0