include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    avoid_print: ignore
    unawaited_futures: error
    unused_import: error
    unnecessary_null_comparison: error
    dead_null_aware_expression: error
    missing_required_param: error

linter:
  rules:
    unawaited_futures: true
    always_use_package_imports: true
    cast_nullable_to_non_nullable: true
    unnecessary_null_checks: true
    require_trailing_commas: true
