stripe_key = "STRIPE_RK_PLACEHOLDER"
twilio_sid = "TWILIO_SID_PLACEHOLDER"
twilio_secret = "TWILIO_SECRET_PLACEHOLDER"

[fb_prod_key]
type = "service_account"
project_id = "juntochat"
private_key_id = "FB_PROD_PRIVATE_KEY_ID_PLACEHOLDER"
private_key = "FB_PROD_PRIVATE_KEY_PLACEHOLDER"
client_email = "firebase-adminsdk-objsj@juntochat.iam.gserviceaccount.com"
client_id = "101146327036562367521"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-objsj%40juntochat.iam.gserviceaccount.com"

[fb_dev_key]
type = "service_account"
project_id = "juntochat-dev"
private_key_id = "FB_DEV_PRIVATE_KEY_ID_PLACEHOLDER"
private_key = "FB_DEV_PRIVATE_KEY_PLACEHOLDER"
client_email = "firebase-adminsdk-1zwse@juntochat-dev.iam.gserviceaccount.com"
client_id = "113769515393808457925"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-1zwse%40juntochat-dev.iam.gserviceaccount.com"