name: functions
description: Cloud functions
publish_to: none

environment:
    sdk: '>=2.17.0 <3.0.0'

dependencies:
    enum_to_string: ^2.0.1
    get_it: ^7.2.0
    googleapis: ^13.1.0
    googleapis_auth: ^1.5.0

    firebase_functions_interop:
        git:
            url: https://github.com/berkmancenter/firebase-functions-interop.git
            branch: master
    data_models:
        path: ../../data_models
    firebase_admin_interop:
        git:
            url: https://github.com/berkmancenter/firebase-admin-interop.git
    node_interop: ^2.0.2
    node_http:
        git:
            url: https://github.com/berkmancenter/node-interop.git
            path: node_http
    intl: ^0.19.0
    timezone:
        git:
            url: https://github.com/berkmancenter/timezone.git
    jaguar_jwt: ^3.0.0
    quiver:
        git:
            url: https://github.com/berkmancenter/quiver-dart.git
    uuid: ^4.1.0
    frankly_matching:
        path: ../../matching
    encrypt: ^5.0.3
    clock: ^1.1.0
    freezed_annotation: ^2.4.1
    freezed: ^2.4.7
    xml: ^6.5.0
    collection: ^1.19.0
    http_parser: ^4.1.0

dev_dependencies:
    build_runner: ^2.0.6
    mocktail: 1.0.3
    test: ^1.17.10
    build_node_compilers:
        git:
            url: https://github.com/berkmancenter/node-interop.git
            path: build_node_compilers
            ref: fix-build-node-compilers
    flutter_lints: ^3.0.1

dependency_overrides:
    quiver:
        git:
            url: https://github.com/berkmancenter/quiver-dart.git
