include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
  errors:
    import_of_legacy_library_into_null_safe: ignore
    invalid_annotation_target: ignore
