site_name: Frankly 💬
docs_dir: pages
site_dir: output
strict: true
theme:
  name: material
  features: 
    - content.code.copy
    - navigation.sections
markdown_extensions:
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true 
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true