name: Playwright Tests
concurrency: staging
on: workflow_dispatch

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: staging
    defaults:
        run: 
          working-directory: client/e2e
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env: 
        CI: 'true'
        TEST_OWNER_USER_NAME: ${{ secrets.TEST_OWNER_USER_NAME }}
        TEST_OWNER_PASSWORD: ${{ secrets.TEST_OWNER_PASSWORD }}
        TEST_MEMBER_USER_NAME: ${{ secrets.TEST_MEMBER_USER_NAME }}
        TEST_MEMBER_PASSWORD: ${{ secrets.TEST_MEMBER_PASSWORD }}
        TEST_COMMUNITY_NAME: ${{ vars.TEST_COMMUNITY_NAME }}
        TEST_COMMUNITY_TAGLINE: ${{ vars.TEST_COMMUNITY_TAGLINE }}
        TEST_COMMUNITY_URL: ${{ vars.TEST_COMMUNITY_URL }}
        BASE_URL: ${{ secrets.APP_STAGING_FULL_URL }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: client/e2e/playwright-report/
        retention-days: 30
